openapi: 3.0.0
info:
   title: Material Dukan CMS
   description: CMS will provide all data about products with crud operations
   version: 1.0.0

servers:
   - url: http://localhost:8000/api
     description: this is the api end point initilization
   - url: http://localhost:8000/api
     description: staging url will be mentioned soon
